### ISSUE TITLE
[BUG] - All Lukkit Gloabls are null.

### ISSUE THREAD

**Issue by Rusketh** [jammehcow/Lukkit#2]
![2016-02-16_14-10-58](https://cloud.githubusercontent.com/assets/1250854/13079030/1fe053f4-d4ba-11e5-9f34-a3703f7bb5de.png)

As shown by the above picture '_G.lukkit' is null as well as '_G.events'.

I know that this plugin is made for 1.79 and I am trying to use it for 1.8.8 (as you can see the plugin still loads and runs a simple lua file with out error). 

I would be happy to fix this myself but sadly I am unable to figure out how to get LuaJ working in any of my projects (thus me using this plugin).

**Comment by martijn-heil** [comment]
What exact Lukkit version are you on?
