### ISSUE TITLE
Option to disable /lukkit run.

### ISSUE THREAD

**Issue by martijn-heil** [jammehcow/Lukkit#4]
I think it would be a good idea to add a configuration option to disable/enable the `/lukkit run` command, and preferably, have it disabled on default.
I find it really _insecure_ to allow any server operator to execute any Lua code, especially when a server instance runs with elevated privileges. Usually, server operators are trusted people, but what if an attacker somehow gets server operator access? The damage would be **way** worse than usual, as it would not be limited to the Minecraft server, but to the whole machine, or even network. An attacker with server operator access could, for instance, install a virus on the machine with some simple Java Standard Library calls.

**Comment by martijn-heil** [comment]
By the way, awesome that you picked up development again :smiley:

**Comment by jammehcow** [comment]
Thanks mate, I enjoy this stuff. Apologies for not reading this sooner, for some reason it didn't notify me.

There's two ways we can go about this (technically three when combined):

1. Implement a config options like you discussed
2. Implement a permission node for permission based usage
3. Implement both

I'm happy to leave that choice up to you.
Thanks for the request.

**Comment by martijn-heil** [comment]
The configuration option for sure, ensuring the security part. All Lukkit commands are administrative commands anyway, so the single permission `lukkit.command` is quite good in my opinion, for simplicity.

**Comment by jammehcow** [comment]
Will be released in 1.1.2 tomorrow - implementing config option and permission node.
Cheers for the feedback!
